### ISSUE TITLE
shortcuts, dockable? custom image sizes ?

### ISSUE THREAD

**Issue by 2blackbar** [ArtBIT/stable-gimpfusion#1]
a lot of stuff is missing, you plan to add custom image sizes and make it dockable so we dont have to click on it everytime to use it ?

**Comment by ArtBIT** [comment]
Custom image sizes are fairly easy to add so I might do that. As for for everything else - sorry, but probably not. 

Gimp plugins cannot be dock-able. They are executed as separate processes so their UI cannot be integrated in the main UI.
Also, creating anything even slightly more complex than what I have, would involve building the UI manually using GTK, which is a lot more complex. 

My aim was never to recreate the whole Automatic1111's Web UI in Gimp. What's the point? You already have the web UI.
I just needed basic StableDiffusion integration to augment my Gimp workflow.

I am hoping that this plugin will give other people a starting point, and inspire them to build something better.

**Comment by 2blackbar** [comment]
can you at least make it not disapear once it generates image? its annoying having to pick img2img all the time

**Comment by ArtBIT** [comment]
I don't think it's what majority of the people want.

If you don't like clicking the menu, just bind a keyboard shortcut to a function.
Go to "Edit > Keyboard Shortcuts" and then search for "StagleGimpfusion" and bind a shortcut key to "Img2Img"
I have the following bindings:
 - Ctrl+Alt+1 TextToImage
 - Ctrl+Alt+2 ImageToImage
 - Ctrl+Alt+3 Inpainting
 
 I also use batch generation quite a bit. I generate images in batches of 5-10.

**Comment by 2blackbar** [comment]
yeh but it would be convenient to do it without touching keboard, some kind of menu option to disable or enable script to trigger shortcut that opens img2img again after it generated image or something,

**Comment by ArtBIT** [comment]
I am not aware of any way to do it using the GIMP plugin system. To my knowledge, you cannot keep the plugin window open, and you cannot re-open it programmatically.
