### ISSUE TITLE
Plugin not showing up

### ISSUE THREAD

**Issue by rincewind0803** [ArtBIT/stable-gimpfusion#2]
Forgive me if i'm dumb, but is there any gimp version requirement ?
I'm on Ubuntu 22.10 gimp 2.10.32 plugin is in ~/.config/GIMP/2.20/plug-ins but i got no menu entry at all.

**Comment by ArtBIT** [comment]
Do you have GIMP with python support? (You should see `Filters>Python-fu>Console` in the menu)
Does the plugin file `stable-gimpfusion.py` have executable flag? (`chmod +x ~/.config/GIMP/2.20/plug-ins/stable-gimpfusion.py`)
Is the plugin folder that you are using (`~/.config/GIMP/2.20/plug-ins`) listed in the GIMP's plug-ins folders? (`Edit>Preferences>Folders>Plug-Ins`)

**Comment by kav** [comment]
Running with verbose I'm seeing this error on MacOS:
```
Querying plug-in: '$HOME/Library/Application Support/GIMP/2.10/plug-ins/stable-gimpfusion.py'
GIMP-WARNING: gimp: gimp_wire_read(): error

Terminating plug-in: '$HOME/Library/Application Support/GIMP/2.10/plug-ins/stable-gimpfusion.py'
```

Not super useful info and no additional info tracing the error further with DEBUG envvars

**Comment by rincewind0803** [comment]
> Do you have GIMP with python support? (You should see `Filters>Python-fu>Console` in the menu)

I was todays days old to learn Ubuntu dropped python2 support so i have to use the flatpack version.

**Comment by kav** [comment]
Yep, MacOS Gimp still has python2 bundled

**Comment by ArtBIT** [comment]
It should now work in OSX.
Can you please update the plugin and check? @kav

**Comment by kav** [comment]
That fixed it for me! Thanks so much @ArtBIT
