### ISSUE TITLE
how i can inpaint just part of the image? using selection doesnt work 

### ISSUE THREAD

**Issue by 2blackbar** [ArtBIT/stable-gimpfusion#4]
is that possible ?i generate portrait of a person but then i drtaw a headband, so i want to now inpaint just headband and select it by rectangle so it inpaionts just this area of forehead, doesnt work tho.inpaints whole image

**Comment by ArtBIT** [comment]
You select the region and choose StableGimpfusion -> Inpaint from the menu:

https://user-images.githubusercontent.com/184220/229197426-4fec6b50-a29b-42e8-8dfe-ad0c5a819459.mp4

**Comment by 2blackbar** [comment]
thanks
