### ISSUE TITLE
ControlNet OpenPose not working to me

### ISSUE THREAD

**Issue by teherauto** [ArtBIT/stable-gimpfusion#5]
Hi,
I try to inpainting with OpenPose, but failed.
What do I do wrong?
Thanks,
Barnabás

[Error.log](https://github.com/ArtBIT/stable-gimpfusion/files/11359412/Error.log)
![Gimp_inpainting_settings](https://user-images.githubusercontent.com/6264591/235308468-24a1f428-2a8d-42cc-aead-a6eb771146de.png)
![Gimp_openpose_layer_settings](https://user-images.githubusercontent.com/6264591/235308470-9f99a6e5-f6ad-47ed-bbb5-510510243165.png)

**Comment by ArtBIT** [comment]
I just tried it with exactly the same settings and it works for me. The only difference is in the openpose model. I am using `control_openpose-fp16.safetensors` , maybe the problem is in the model?

**Comment by teherauto** [comment]
I try the V1.1 OpenPose model, but the same error: AttributeError: 'str' object has no attribute 'enabled'. I think the problem will be somewhere else. Thanks for your help, I try re-install everything.

**Comment by ArtBIT** [comment]
[control_openpose-fp16.safetensors](https://huggingface.co/webui/ControlNet-modules-safetensors/tree/main) is `v1` not `v1.1`

I haven't yet tried using `v1.1` ControlNet, they might have changed the API, in which case this plugin will fail.

**Comment by teherauto** [comment]
Yes, this is possible, as a lot has changed between 1.0 and 1.1.

**Comment by adamtwatson** [comment]
Hi, 
There was a modification to the https://github.com/Mikubill/sd-webui-controlnet library changing the location of where txt2img and img2img when using controlnet, see documented change here: https://github.com/Mikubill/sd-webui-controlnet/wiki/API#web-api
